apiVersion: batch/v1
kind: Job
metadata:
  name: madgraph-job-gg
  labels:
    jobgroup: madgraph-job
spec:
  template:
    spec:
      containers:
      - name: madgraph-time
        image: hfukuda/madgraph:latest
        command:
        - "/bin/bash"
        - "-c"
        - " git clone https://github.com/jmduarte/madgraph-time &&
            time madgraph-time/ppTOgg_13TeV/bin/generate_events -f"
        resources:
          limits:
            memory: 32Gi
            cpu: "16"
            nvidia.com/gpu: "0"
          requests:
            memory: 16Gi
            cpu: "8"
            nvidia.com/gpu: "0"
      restartPolicy: Never
  backoffLimit: 5
